betagouv/france-chaleur-urbaine

yarn.lock
Minimist <=1.2.5 is vulnerable to Prototype Pollution via
file index.js, function setKey() (lines 69-95).
=> Fix: Upgrade Minimist (and other deps)

src/components/Map/components/SummaryBoxes.tsx, src/core/infrastructure/repository/dataSummary.ts
Pour la requête de téléchargement des données d'une zone, permet de passer de 1.1 minute à 4.6s chez moi.
Car on utilise l'index géospatial.
- utilisation de st_dwithin qui permet d'utiliser les indexes directement
- pas de transformation de la geom des rdc car elle est déjà en projection Lambert, sinon l'index ne peut pas être utilisé directement.
- fix du spinner qui continue de tourner en cas d'erreur
=> fix: optimisation performances dans les calculs de distance

docs/import_reseau_chaleur.md, scripts/copyLocalNetworkToRemote.sh
2-3 corrections / maj + **ajout d'un script pour dumper les tables en local et les importer sur les environnements cibles**.
- Chez moi j'ai besoin de spécifier la clé SSH utilisée car ce n'est pas celle par défaut (~/.ssh/id_rsa) que j'utilise... cf [code scalingo](https://github.com/Scalingo/cli/blob/9b80d09bca6b25f25af053655bf54fc09fa0249c/cmd/db_tunnel.go#L65)
- Aussi, chez moi j'ai editorconfig qui supprime les espaces en fin de ligne. Ça vaudrait le coup d'ajouter une petite config dans le projet.
=> fix: amélioration procédure import réseau

src/components/Map/components/LegendEntry.styled.ts
Je trouve la vie plus simple avec cette modification, sinon il faut être super précis pour cocher la case...
[fcu-label-layers.webm](https://github.com/betagouv/france-chaleur-urbaine/assets/8938024/6b7aba1f-59d4-4950-9404-07fc56fe8091)
=> feat: utilisation du label pour sélectionner les layers

src/data/coproprietaire/user-experience.js
Sur la page principale, passe de :
à :
C'est clairement pas pratique de styler le markdown, avec les styles globaux :-/
=> fix: taille police xp utilisateur

src/components/Map/StyleSwitcher/index.ts
Suite à la maj de version de maplibre et maj des types, j'avais repris le fichier. Sauf que je n'avais pas fait les modifications de classes mapbox vers maplibre.
Désormais le switcher apparait bien !
=> fix: update StyleSwitcher CSS classes

src/services/matomo.ts
Supprime le '?' encodé dans les paramètres urls[*]
=> fix: matomo query

next.config.js, src/components/Statistics/Statistics.tsx
- Dès qu'on change qqch sur l'URL de matomo ou l'id du site, il faut mettre à jour la CSP policy :grimacing: 
- L'année 2024 avec des valeurs vides fait planter la page stats. Comme on affiche a priori le mois précédent, j'ai masqué l'année 2024 pour l'instant. Le bug reviendra peut-être en février (sûrement en fait comme il n'y aura pas de nouvelles données sur stats.data.gouv.fr...)
=> fix: matomo csp and page stats

src/client-config.ts, src/components/Map/components/SummaryBoxes.tsx, src/config.ts, src/core/infrastructure/repository/dataSummary.ts, src/pages/api/map/summary.ts
:warning: A merger après la révision BDNB 2022 sur dev pour s'assurer que l'export est ok aussi. (actuellement les colonnes n'ont pas les bons noms)
L'empire contre attaque avec le st_dwithin qui revient.
- J'ai supprimé les transformations inutiles vers le srid 2154 quand les geom le sont déjà.
- Il y a seulement la geom_adresse qui est en lat lon (4326), et j'y ai mis un commentaire pour spécifier le srid d'origine.
J- 'ai remanié un peu la limite de surface pour avoir une seule config. J'ai mis ça dans un fichier src/config.ts ne sachant pas où le mettre.
Idéalement, j'aimerais bien mieux distinguer ce qui est côté front, côté back, et ce qui est partagé entre les 2. Affaire à suivre... :smile: 
J'ai testé le summary des bâtiments et l'export en local avec la BDD de prod et en local …
=> feat: rerevert st_distance => st_dwithin

Procfile, docs/import_bdnb.md, docs/import_reseau_chaleur.md, package.json, scripts/addUser.ts, scripts/downloadNetworks.ts, scripts/fillTiles.ts, src/cron_jobs/manual-job.ts, src/db/index.ts, yarn.lock
Concernant le revert du logger, en fait je n'avais pas fait attention qu'il y avait d'autres process (bonjour le cron et les scripts exécutés en local) qui passaient par ts-node. Ce dernier ne gère pas très bien (ou facilement en tout cas) la configuration un peu exotique typescript.
Donc je le remplace par [tsx](https://github.com/privatenumber/tsx/), qui set basé sur esbuild (il existe aussi tsup), qui va chercher automatiquement dans la conf ts pour résoudre les alias notamment.
~~A priori, on a peut-être plus besoin du NODE_PATH, mais il faudra tester sur scalingo...~~
=> test sur scalingo réalisé, le cron se lance bien.
=> En local, je n'ai pas eu de problème pour lancer un script comme downloadNetworks, mais ça serait bien si tu pouvais tester des commandes susceptibles de planter …
=> chore: migrate from ts-node to tsx

package.json, yarn.lock
En fait knex a besoin de ts-node pour fonctionner*... et n'utilise pas tsx.
* pour corriger `yarn db:migrate`
=> fix: install ts-node for knex

src/pages/api/airtable/records/index.ts
Evite une erreur à la création d'une demande quand l'adresse est dans la BDNB.
=> fix: convert airtable 'ID BNB' to string

src/hooks/useContactFormFCU.ts
Les events en "inéligible" ne fonctionnaient pas depuis un bout de temps a priori.
=> fix: use the correct isEligible variable for analytics events

src/pages/map.tsx
Exemple : /map?legend=true&displayLegend=reseau_chaleur
=> fix: don't display 'potentiels de raccordements' on iframes

knexfile.ts
Permet de ne plus avoir l'erreur pour la BDD est saturée de connexions en local.
=> refactor: use a pool for pg and timeout idle connections

src/pages/api/modification-reseau.ts, src/pages/api/networks/search.ts, src/pages/reseaux/modifier.tsx
Corrige les problèmes ci-dessous :
Sur le formulaire de modification de la fiche réseau
- le champ Site internet ne doit pas être obligatoire (tous les réseaux n'ont pas de site internet, et on tient pas absolument à renvoyer vers des sites externes par ailleurs)- désolée j'avais pas fait attention à ça lors de la validation
- il ne doit pas non plus être obligatoire d’ajouter un texte, certaines personnes voudront juste modifier une info erronée
Quand on clique sur non classé au lieu de classé sur le formulaire de contact, cela n'est pas enregistré dans le airtable : la cache classé est toujours cochée
=> fix: corrections formulaire modif réseau

src/components/ui/Text.tsx, src/pages/collectivites-et-exploitants.tsx
Un oubli parmi les nombreux retours de la PR des modifs de réseau, qui m'est revenu ce matin à la démo de Florence.
Permet de passer de 
à
=> style: arrange la couleur d'un label page exploitants

.gitignore, next.config.js, package.json, sentry.client.config.ts, sentry.edge.config.ts, sentry.server.config.ts, src/helpers/server.ts, src/pages/404.tsx, src/pages/_error.jsx, yarn.lock
Permet de remonter toutes les erreurs UI et API à Sentry.
J'aurais voulu utiliser l'option de tunnel pour ne pas utiliser sentry.incubateur.net directement et devoir modifier la CSP, mais rien ne marchait donc j'ai abandonné.
J'ai également ajouté un composant Error next et une page 404 minimale.
C'est la conf par défaut de Sentry.
Il restera plus qu'à configurer la fréquence des notifications sur Sentry pour ne pas être spammés et on pourra aller y faire un tour pour corriger des erreurs de temps en temps.
Pour activer, il suffit d'ajouter la variable d'env NEXT_PUBLIC_SENTRY_DSN=https://5e0185d628be41bb8372d7725219d950@sentry.incubateur.net/139 au fichier .env.local. et il faudra l'ajouter en prod (+ dev peut-être, ou bien avoir une 2e site pour le dev ?)
=> feat: integrate sentry

scripts/cli.ts, scripts/downloadNetworks.ts, scripts/networks/download-network.ts, src/components/Map/components/MapPopupContent.tsx, src/db/migrations/20240131000000_cleanup_rdc_commentaires_date.ts, src/services/tiles.config.ts
- Supprime les champs commentaires et date de la table network (réseau de chaleur). Ils étaient toujours vides.
- Corrige la commande yarn cli fill-tiles qui ne supprimait pas les tuiles au préalable (car update on conflicts ignore...). J'ai ajouté le delete all. Ça vaudra le coup d'améliorer le mécanisme pour ne pas tout supprimer et tout recréer.
=> fix: impacts nettoyage airtable

knexfile.ts
Il y a parfois des erreurs en prod sur des délais d'acquisition d'un client postgres, sachant que la carte utilise la BDD pour les tuiles, ça peut monter très rapidement pour des requêtes très courtes.
Ici on augmente à 60, sachant qu'il peut y avoir plusieurs instances (5 max pour le moment), et que la BDD permet 480. C'est une valeur raisonnable qui permet de laisser des connexions ouvertes pour s'y connecter à côté.
=> chore: increase db pool size

src/helpers/logger.ts, src/helpers/server.ts, src/pages/api/map/[type]/[...tileCoordinates].ts
Un petit log de la durée de traitement de chaque route pour avoir des informations si besoin.
Désactivé pour les requêtes de récupération des tuiles car pas intéressant (trop nombreuses et très rapides)
Toutes les routes n'utilisent pas encore `handleRouteErrors()`, mais ça viendra petit à petit avec l'uniformisation de la gestion des erreurs.
=> feat: add requests logging

src/components/Statistics/Statistics.tsx, src/pages/_app.tsx, src/pages/api/statistiques/actions.ts, src/pages/api/statistiques/visits.ts, src/pages/api/statistiques/visitsMap.ts, src/services/matomo.ts, src/services/matomo_types.ts
Une petite PR pour proposer une simplification du code pour les statistiques, majoritairement côté API. Il y a 3 commits que tu peux regarder à la suite.
- le 1er supprime la duplication (un peu trop poussée) entre les 3 routes qui utilisent matomo (notamment la génération de la liste des mois)
- j'ai regroupé la logique client d'API matomo dans src/services/matomo.ts qui fait toujours des bulk requests (ainsi, on a toujours un tableau de résultats).
- le 2e supprime la propriété results sans doute héritée / inspirée de l'API matomo. Maintenant le résultat (tableau) est directement envoyé
- le 3e simplifie la gestion des erreurs côté UI et ajoute du typage (un minimum car beaucoup d'objets ont des noms de propriétés dynamiques).
- côté erreurs : si l'API retourne une erreur (statut !== …
=> refactor: improve matomo error handling

src/core/infrastructure/repository/manager.ts, src/helpers/server.ts, src/pages/api/auth/[...nextauth].ts, src/pages/api/demands/[demandId].ts, src/pages/api/demands/index.ts, src/pages/api/eligibilityDemands.ts, src/pages/api/users.ts, src/services/api/authentication.ts, src/types/User.d.ts
- dans le callback session de next-auth, j'ai ajouté la récupération de l'utilisateur depuis postgres, via son email (stocké dans le cookie de session, avec d'autres données de l'utilisateur) + mise à jour de last_connection
- dans le helper handleErrors qui gère les erreurs et simplifie pas mal de choses, j'ai ajouté une option pour les routes qui demandent une authentification et/ou des permissions spécifiques (comme un rôle particulier)
- l'utilisateur de la session (à jour) est forwardé via req.user au cas où une route doive accéder à plus de choses, par exemple pour vérifier que les tags gestionnaires correspondent bien à la ressource accédée.
- j'ai revue la gestion des erreurs de quelques routes, et pour avoir des logs. :upside_down_face: 
J'ai testé sur ma base de dev airtable :
- …
=> fix: fetch the user from the db in next auth middleware

next.config.js
Modification afin d'autoriser le générateur de doc OpenAPI de api.gouv.fr d'accéder à notre schéma openapi.
=> fix: openapi schema CORS

src/components/EligibilityForm/components/ContactForm.tsx, src/components/HeadSliceForm/HeadSliceForm.tsx, src/components/IFrame/Form/Eligibility.styles.ts, src/components/IFrame/Form/Eligibility.tsx, src/services/analytics.ts
Ajout d'ids sur les formulaires de test d'adresse + contact (demandes) afin qu'Arnaud puisse paramétrer le suivi côté Matomo.
J'ai utilisé un enum TS car je n'ai pas surchargé le typage des ids HTML (trop de composants), sinon j'aurais simplement fait un string union type :grinning:
=> feat: add form ids

src/components/IFrame/Map/IFrameMapIntegrationForm.tsx, src/components/IFrame/Map/IFrameParametrization.tsx, src/hooks/useInitialSearchParam.ts, src/hooks/useURLParamOrLocalStorage.ts, src/pages/carte.tsx
Sur la page /carte, nouveau paramètre `additionalLayers` pour afficher des couches par défaut. 
L'objectif est de partager via la communication un lien vers la carte avec une couche active quand on ajoute une nouvelle couche de données.
Il n'y avait pas de besoin de synchroniser la configuration de la carte dans l'URL pour le moment, donc c'est juste des couches supplémentaires affichées.
=> feat: add param additionalLayers carte

src/components/Admin/UserImpersonation.tsx, src/components/shared/page/SimplePage.styles.tsx, src/components/shared/page/SimplePage.tsx, src/helpers/server.ts, src/pages/admin.tsx, src/pages/api/admin/impersonate.ts, src/pages/api/admin/tags-gestionnaires.ts, src/pages/api/auth/[...nextauth].ts, src/types/NextAuth.d.ts, src/utils/network.ts, src/utils/strings.ts
Un admin peut maintenant se faire passer pour un utilisateur gestionnaire avec les tags gestionnaire qu'il souhaite. Permet de se passer de tous les comptes de ville et reproduire des cas particuliers sans avoir à créer de compte.
Le fonctionnement est le suivant :
- L'utilisateur (admin) envoie une requête à l'API avec le role (uniquement gestionnaire) et les tags souhaités.
- Une nouvelle session est générée et contient l'information d'imposture du profil.
- Dans les middlewares / callbacks next auth, si cette information est présente, alors on remplace les données de l'utilisateur par celles-ci, de sorte qu'elles soient disponibles partout comme si l'utilisateur avait rééllement changé de profil.
- Côté UI, on sait néanmoins qu'on est en mode imposture avec une propriété …
=> feat: impostures de profils

package.json, yarn.lock
Supprime [ce warning](https://github.com/betagouv/france-chaleur-urbaine/security/dependabot/29) affiché également à chaque push git.
J'ai testé un export xlsx de l'espace gestionnaire, ça fonctionne toujours. :smile:
=> fix: dependabot warning about sheetjs

src/components/Manager/ModalEmails.tsx, src/pages/aide.tsx
- Ajout d'un champ "À" non modifiable avec l'adresse email de l'utilisateur
- Mise à jour de l'aide
=> fix: In manager emails add disabled field 'to' + update help page

src/core/infrastructure/repository/addresseInformation.ts
La colonne "Tracé non disponible" est supprimée
Si on est sur un tracé non disponible mais présent à l'iris, dans la colonne Distance : "Non disponible"
=> fix : remove 'Tracé non disponible mais présence d'un réseau dans la zone

src/pages/actus/[slug].tsx
Basé pour le moment sur #747 pour avoir les thèmes par actualité et ne contient en réalité qu'un seul [commit](https://github.com/betagouv/france-chaleur-urbaine/pull/748/commits/709df58bc1f4a2608434d829846f131e77ef8646?w=1) (avant des potentiels retours).
Transforme ça :
en ça :
=> feat:  revue style page actu

src/components/Map/components/SimpleMapLegend.tsx, src/pages/professionnels.tsx
Plutôt que de créer un fichier qui serait mis à jour côté data.gouv, dupliqué à côté des versions historisées, on redirige maintenant sur la page de data.gouv et on sort l'archive du code.
=> feat: update opendata link (last update!)

public/img/polygon-zonesPotentielChaud.svg, public/img/polygon-zonesPotentielFortChaud.svg, scripts/cli.ts, scripts/copyLocalTableToRemote.sh, scripts/fillTiles.ts, scripts/networks/download-network.ts, scripts/utils/tiles.ts, src/components/Map/Map.style.tsx, src/components/Map/Map.tsx, src/components/Map/components/DynamicMapPopupContent.tsx, src/components/Map/components/IconPolygon.tsx, src/components/Map/components/SimpleMapLegend.tsx, src/components/Map/map-layers.ts, src/pages/api/map/[type]/[...tileCoordinates].ts, src/services/Map/businessRules/enrrMobilisables.ts, src/services/Map/businessRules/zonePotentielChaud.ts, src/services/Map/map-configuration.ts, src/services/analytics.ts, src/services/tiles.config.ts, src/services/tiles.ts, src/types/layers/enrr_mobilisables.ts, src/utils/strings.ts
- 2 nouvelles couches dans la section ENRR mobilisables, propices à l'installations de panneaux photovoltaïques (récupérées et intégrées de la même façon que les autres ENRR) :
- friches
- parkings de + de 500m² 
- Un composant IconPolygon qui prend une couleur en paramètre, car le comportement est identique à d'autres couches de zone (zones d'opportunités).
- Petit refacto sur DataType qui est en fait un SourceId (potentiellement même TileSourceId...)
- Nouveau script que j'ai utilisé pour synchroniser ~en mode bourrin~ mes 2 tables locales vers l'env de dev ~(ça drop complètement). J'imagine qu'un jour, on aura intérêt à avoir un script qui fait ça mais en renommant tout bien sans risque de downtime sur la table cible)~. Il y a 2 modes, un pour créer aussi la structure, l'autre pour ne …
=> feat: intégration des couches friches et parkings

src/components/ui/Link.tsx, src/pages/ressources/outils.tsx
Corrige les liens vers des ancres, notamment à partir de la page outils vers le simulateur CO2, iframes, etc
=> fix: anchor scrolling

src/components/Map/components/SimpleMapLegend.tsx, src/pages/carte.tsx, src/services/Map/map-configuration.ts, src/utils/typescript.ts
Permet de restreindre les propriétés retournées par le FlattenKeys afin de limiter les risques d'erreur quand on met à jour la conf.
A permis de détecter une erreur au niveau du mapping URL => couche affichée.
=> chore: ajout typing sur MapConfigurationProperty

.vscode/extensions.json, .vscode/settings.json
Recommandes les extensions Prettier et ESLint avec des réglages de base.
A compléter si besoin.
=> add vscode configuration

src/core/infrastructure/repository/addresseInformation.ts
Permet d'utiliser l'index pour calculer la distance.
Permet de passer de 100/120ms à 15/20ms pour la table reseaux_de_chaleur.
=> perf: optimisation performances requête calcul distance

src/components/Network/Network.tsx
Permet d'éviter d'afficher les informations complémentaires en ajoutant un paramètre comme pour les autres sections.
C'est [utilisé uniquement par Engie](https://www.rezomee.fr/velizy-reseau-chaleur/plan-reseau), et on ne veut pas faire de pub donc ce n'est pas documenté...
=> fix: suppression du bloc informations si pas demandé

src/components/Map/Map.tsx, src/utils/core.ts
Besoin de #787 pour réorganiser les imports de Map.tsx
- Petite correction de deepMergeObjects  pour utiliser cloneDeep pour être sûr que l'objet en paramètre n'est pas muté.
- Une fois les limites des filtres récupérées, on les applique à la configuration. Jusqu'à présent, c'est le composant RangeFilter qui s'en occupait (et c'était donc pas génial...)
=> fix: apply range limits to the filters

src/components/Map/Map.tsx
Corrige le zoom à 16 sur les fiches réseau, au lieu de 13, surtout visible en prod.
Pour reproduire en local, j'ai dû activer un outil de tracking (linkedin par exemple).
=> fix: zoom initial carte fiches réseau

src/core/infrastructure/repository/addresseInformation.ts, src/pages/api/map/bulkEligibilityStatus/index.ts, src/pages/api/map/eligibilityStatus.ts, src/services/heatNetwork.ts
- Basé sur #779 car il y a quelques changements liés au test d'éligibilité.
- Supprime la ville des paramètres du test d'éligibilité. Les seuils réduits à 100m/60m sont seulement valables pour les réseaux 7501C et 7511C (Paris) (vu avec Florence)
- j'ai pas complètement enlevé la ville du bulk, pour avoir moins d'impacts
=> Fix harmonisation éligibilité api formulaire

src/components/Map/Map.tsx, src/services/Map/map-configuration.ts
Je suis sur la carte en mode pro. Je désactive le mode pro : pas de pb cela fonctionne. Je ferme l’onglet. Je rouvre l’onglet (ou bien simplement, je vais sur une autre page du site puis reviens sur la carte) : mon choix est bien enregistré (mode pro désactivé), la légende est OK (mode pro désactivé) en revanche les données du mode pro apparaissent sur la carte (consos gaz, bât à chauffage collectif gaz et fioul). Je dois réactiver et redésactiver pour qu’elles ne s’affichent plus…
=> Solve bug pro mode

src/components/Network/Network.tsx
Bon j'ai été un peu trop vite sur les conditions de la fiche réseau... :roll_eyes: 
Transforme `!displayBlocks || (displayBlocks.includes('informations')  && ....)` en `(!displayBlocks || displayBlocks.includes('informations')) && ....` sinon rien ne s'affiche sur la fiche réseau
=> fix: conditions d'affichage des blocs fiche réseau :facepalm:

src/components/connexion/NewPasswordForm.tsx, src/pages/api/password/change.ts, src/pages/api/password/reset.ts, src/services/email/views/password.ejs
- Finalement `jwt.verify` lève une exception plutôt que de renvoyer une valeur vide.
- \+ affichage du message d'erreur zod côté formulaire. (idéalement, il faudrait avoir un comportement similaire pour tous les formulaires
=> feat: affichage message d'erreur détaillé formulaire reset pw

docker-compose.yml
Change le serveur de mail de test utilisé en local par [mailpit](https://mailpit.axllent.org/).
Avantages :
- volume docker pour conserver l'historique des mails
- affiche les pièces jointes directement !
- projet maintenu !
En local, après avoir récupéré cette branche et / ou une fois mergée. Il faudra faire la commande suivante :
```
docker compose up -d --remove-orphans
```
=> feat: replace maildev by mailpit (better ux)

next.config.js, src/client-config.ts, src/components/Markup/GoogleAdsMarkup.tsx, src/pages/_app.tsx, src/services/analytics.ts
Pour william.
Alors, c'est toujours pas l'idéal avec les CSP à changer et les ids à configurer via variable d'env. Mais théoriquement (un jour), on devrait s'en sortir en utilisant les nonces.
=> feat: ajout tag GA4 en plus de AW

src/components/EligibilityForm/EligibilityFormAddress.tsx, src/components/EligibilityForm/EligibilityFormContact.tsx, src/components/HeadSliceForm/HeadSliceForm.tsx, src/components/Map/components/CardSearchDetailsForm.tsx, src/components/Map/components/MapSearchForm.tsx, src/components/Network/EligibilityTestBox.tsx, src/helpers/airtable.ts, src/hooks/useContactFormFCU.ts
- Permet d'afficher un message d'erreur en cas d'erreur sur les formulaires de test d'adresse + demande de contact. Le but étant de ne pas afficher le message comme quoi la demande a été traitée si elle n'est pas enregistrée.
- Il y a pas mal de complexité dans les composants historiques liés au formulaire avec le hook avec beaucoup de callbacks en paramètre de composants, 
- \+ gros bugfix sur les pages avec le sticky form (pages villes + ressources)
- Sur la carte
- Sur les fiches réseau
- Sur les pages vitrines
- Sur les pages ville...
=> feat: gestion basique des erreurs des formulaires de test

src/services/analytics.ts
:sob: Bon en fait j'avais merdé mon correctif sur l'ab testing quand matomo n'est pas joignable.
On passait toujours dans le cas du timeout puis état error (et variation originale). Car la variable est dans une closure et donc ne change pas... :facepalm: 
J'ai ajouté le clearTimeout pour éviter ce cas quand le script est chargé. Et on devrait enfin avoir des chiffres corrects.
=> fix: repair ab testing

src/components/EligibilityForm/EligibilityFormContact.tsx, src/components/HeadSliceForm/HeadSliceForm.tsx, src/components/Map/components/CardSearchDetailsForm.tsx, src/components/SliceForm/SliceForm.tsx, src/components/StickyForm/StickyForm.tsx
Corrige la double soumission des formulaires de contact. Le comportement avait récemment changé pour afficher des erreurs côté API.
Fini les `isLoading=(isSent}` :sweat_smile:
=> fix: prevent forms double submission

.env, src/pages/api/password/reset.ts, src/services/email/index.ts
- Petite modif pout utiliser la nouvelle adresse d'envoi, dont le domaine est authentifié côté Brevo
- Simplification des paramères de connexion / d'envoi d'email
- On conserve l'adresse actuelle en replyTo
- J'ai ajouté un log warning au niveau de l'oubli de mdp (en plus de la ligne dans airtable)
S'assurer d'avoir ça dans le fichier .env.local :
```sh
MAIL_HOST=mailpit
MAIL_PASS=mailpassword
MAIL_USER=mailuser
MAIL_PORT=1025
MAIL_SECURE=false
```
Il faudra mettre à jour les variables en prod au moment du déploiement
=> feat: update mail sender

package.json, src/components/Map/Map.tsx, src/modules.d.ts, yarn.lock
- Feature demandée pour centrer la carte sur des villes avec une bbox calculée au préalable et passée en paramètre.
- Petite lib ajoutée pour s'occuper des calculs magiques pour en déduire le niveau de zoom et le centre de la carte selon les dimensions de la fenêtre et les coordonnées de la bbox.
Exemple avec un lien comme ceci (à adapter à l'environnement de preview) : https://france-chaleur-urbaine.beta.gouv.fr/carte?proMode=true&additionalLayers=enrrMobilisables,zonesOpportunite&bbox=7.13654739520414,43.693165306409476,7.1845181701831775,43.74226983240324
=> feat: ajout param bbox sur la carte

src/components/Hoverable/HoverableIcon.tsx, src/components/Network/Network.tsx, src/components/Statistics/Statistics.tsx
Suite à la migration de la lib DSFR, la PR corrige les icones pages Réseau et Statistiques pour qu'elles aient la même taille qu'en prod actuellement. (déjà ok dans le manager)
=> fix: diminue la taille des icones info

src/components/Map/Map.tsx
Problème dû à la génération des RDC qui utilise `yarn cli generate-tiles-from-file` à cause des métadonnées supplémentaires, donc la sourceLayer dans la tuile s'appelle juste layer (il y en a qu'une seule)
=> fix: style hover des réseaux de chaleur

src/components/Manager/Comment.tsx, src/components/Manager/Manager.tsx
Suite à #842, il ne faut pas recréer de nouveau tableau sinon la datagrid réinitialise se pagination. Donc on mute directement l'objet, sans le splice car datagrid freeze l'objet en dev...
=> fix: évite le reset pagination manager à chaque modif d'une ligne

package.json, src/pages/actus/index.tsx, yarn.lock
Permet de ne pas charger 150 images d'un coup sur la [page actus](https://france-chaleur-urbaine.beta.gouv.fr/actus).
~:warning: Manque encore la mise à jour côté DSFR. cf https://github.com/codegouvfr/react-dsfr/pull/294~
Démo ici => https://france-chaleur-urbaine-dev-pr855.osc-fr1.scalingo.io/actus
=> Lazy loading des images page actu

package.json, src/components/SimulatorPublicodes/TechnicienParametresTechniques.tsx, src/components/SimulatorPublicodes/index.tsx, src/components/form/publicodes/Select.tsx, src/components/form/publicodes/helpers.ts, src/pages/api/location-infos.ts, yarn.lock
Voir les commits:
- corrige les select foireux
- maintenant le formulaire contient que des placeholders quand on choisit la ville.  C'est donc plus simple de revenir à la valeur par défaut
=> Fix select comparateur

src/components/HeadSliceForm/HeadSliceForm.tsx
Corrige un problème avec firefox 115esr qui valide le formulaire nativement sinon et se retrouve sur l'URL avec les paramètres du formulaire.
=> Forcage du type button pour le test d'adresse

src/components/Map/Map.tsx, src/pages/carte-collectivite.tsx, src/pages/charleville-mezieres.tsx, src/pages/dalkia.tsx, src/pages/engie.tsx, src/pages/idex.tsx, src/pages/map.tsx, src/pages/viaseva.tsx, src/services/Map/map-configuration.ts
Plus besoin de proMode dans la MapConfiguration et de withHideLegendSwitch dans Map car plus de bande blanche en haut.
=> Supprime du code lié à l'ancien mode pro de la carte

src/components/Map/Map.tsx
Par défaut, quand on active la géolocalisation via le bouton en haut à droite de la carte, un rond s'affiche et on ne peut plus le supprimer.
Avec cette PR, il devient un toggle et on peut donc le retirer de l'affichage.
=> Autorise la désactivation de la géolocalisation

src/components/Map/map-layers.ts
Suite à la migration DSFR probablement, avant le composant générait des intervalles avec infinity ou max integer il me semble.
Là j'ai préféré ne pas modifier le composant ScaleLegend et la MapConfiguration, car c'était plus rapide là.
=> Correction du filtre consos de gaz

src/core/infrastructure/repository/addresseInformation.ts
Revoit les cas de gestion selon la spécification.
Pour passer de 
à
Pour le futur futur, il faudrait que l'API retourne toutes les infos (réseau existant, en construction, PDP etc), pour que l'UI ait exactement la structure de la spéc.
=> Correction cas éligibilité intermédiaires + commentaires selon spéc

src/components/Network/EligibilityTestBox.tsx, src/components/addressAutocomplete/AddressAutocomplete.tsx, src/components/addressAutocomplete/useSuggestions.tsx, src/types/Suggestions.d.ts
Par défaut le comportement de test d'adresse fonctionne comme ceci :
- On a une adresse globalement précise =>  l'utilisateur a la possibilité de laisser une demande
- On a une ville uniquement => on teste si la ville a un réseau de chaleur ou pas et on invite l'utilisateur à renseigner une adresse plus précise
Sur la fiche réseau, c'est une version différente (simplifiée) du test d'adresse (un peu différent aussi car on teste l'éligibilité avec un réseau en particulier), et on ne gérait pas le cas de test de ville.
~Maintenant, le champ de recherche d'adresse ne retourne que des adresses précises. Je n'ai pas trouvé le moyen de juste exclure les villes...~
~Potentiellement il faudrait peut-être récupérer ces résultats classiquement, mais filtrer côté UI pour supprimer les suggestions de …
=> Test d'adresse uniquement sur la fiche réseau, pas de villes

src/data/statistics.ts
cf données Florence.
A vérifier sur la page /stats
=> Maj statistiques au 17 octobre 2024

src/components/Map/components/tools/LinearHeatDensityTool.tsx, src/components/ui/Icon.tsx, src/db/migrations/20241023000001_add_index_geom_donnees_de_conso.ts, src/pages/api/linear-heat-density.ts, src/services/heatNetwork.ts
- Ajout de cette section à l'interface
- J'en ai profité pour refacto la requête pour récupérer les consommation. J'ai ajouté un index via migration sur la table donnees_de_consos qui divise par + que 100 le temps de requête (100ms => 0.1ms).
- Nouvelle route /api/linear-heat-density plutôt que la route legacy /api/map/summary?type=line qui mix un peu trop de choses. Elle reste pour pas casser la prod pour les utilisateurs sur la carte, mais on pourra retirer la partie line plus tard.
- Les données sont dans la nouvelle table `besoins_en_chaleur_batiments` (+ 9Go). Pour l'assembler => [Notion](https://www.notion.so/D-veloppement-e8399345919442748735de25865ebe4a?pvs=4#129c2b5c414b80e8a296fadbb0fe7e26). Dans le futur on devrait avoir la possibilité de sélectionner les bâtiments pour …
=> Densité thermique linéaire sur besoins en chaleur des batiments

src/components/Ressources/Contents/SimulateurCoutRaccordement.tsx, src/services/analytics.ts
Bon d'après ce que j'ai compris, on ne tracke qu'un seul événement par usage / visite de page. Donc j'envoie un événement dès qu'on touche au formulaire.
Aussi, c'est pas spécifié s'il faut tracker pour chaque page où ce simulateur apparait, donc tant pis. :)
=> Tracking du simulateur de coût de raccordement

src/db/migrations/20241119000001_update_networks_website_type.ts, src/pages/api/networks/search.ts
Petite correction d'un type en base.
Pour info, char(254) = toujours 254 caractères, complétés avec des espaces. J'aurais bien voulu utiliser le type text pour pas s'embêter, mais comme l'équivalent côté reseaux_de_froid est varchar(254), j'ai préféré harmoniser avec.
=> Fix typage website_gestionnaire char => varchar

src/pages/actus/[slug].tsx, src/pages/collectivites-et-exploitants/potentiel-creation-reseau/[[...slug]].tsx, src/pages/reseaux/[network].tsx
Corrige la page active dans la navigation pour /reseaux/id, /actus/id et /collectivites-et-exploitants/potentiel-creation-reseau
Avec next et dsfr, pas de router spécial ou on peut dire isActive exactMatch etc.
J'ai regardé pour surcharger le type côté navigation dsfr, mais c'était chiant...
Donc là je réutilise le param currentPage de SimplePage qui permet d'activer manuellement une page de la navbar.
=> Fix page active de 3 pages

scripts/cli.ts
- Grâce au parseAsync, ça gère mieux les actions asynchrones.
- On log l'erreur avec à la console, et ça log aussi les autres champs qui peuvent être utiles.
=> Centralisation de la gestion des erreurs CLI

src/components/Network/Network.tsx, src/components/ui/Box.tsx
Permet de passer de 
à
overflow hidden permet au texte d'être coupé un peu n'importe où. J'ai pas mis d'ellipsis non plus car c'est bien de voir le lien je pense. Ou sinon il faudrait voir le début et la fin.
J'ai permet une fonction valueRenderer pour surcharger l'élément wrapper. J'aurais bien voulu juste pouvoir remplacer l'élement, sans utiliser de fonction, mais j'ai pas réussi avec typescript, donc si t'as des idées, je suis preneur. :)
=> Amélioration affichage lien site gestionnaire

src/components/Map/components/tools/LinearHeatDensityTool.tsx
Le format était mauvais. Maintenant ça fonctionne correctement. Même si le SRID n'est pas mentionné.
=> Fix format geojson à l'export du tracé

src/components/Map/map-hover.ts, src/components/Map/map-layers.ts
Y'avait pas besoin de créer une 2e couche en fait donc j'ai supprimé ça.
Là on complète juste la fonction qui transforme les filtres en expressions mapbox.
=> Fix filtre réseau classé sur réseau sans tracé

src/core/infrastructure/repository/networksListToCompare.ts
Evite d'afficher des 0 quand pas de valeur définie. sur la liste des réseaux notamment pour Quimper 2910C.
=> Fix null * 1000 = 0 => null

src/components/Map/MapProvider.tsx, src/components/Map/layers/filters.ts, src/components/Map/map-configuration.ts, src/server/helpers/fileio.spec.ts
Maintenant on a le filtre global mapConfiguration.filtreGestionnaire et celui spécifique à la couche rdc mapConfiguration.reseauxDeChaleur.gestionnaires. C'est ce dernier qui est piloté via l'interface. Le 1er est pour le moment uniquement utilisé pour pré-filtrer les iframes.
=> Fix le filtre gestionnaire RDC dans les iframes

src/server/cron/cron.ts
Pour éviter que le cron se lance dans les instances web et seulement dans la clock
=> Fix cron import

src/components/NetworksList/NetworksList.tsx
quand on filtre meme les valeurs nulles sonta ffichées alors qu'elles ne devraientt pas
https://trello.com/c/JZfBrMsN/1424-bug-sur-filtres-sur-la-liste-des-r%C3%A9seaux
=> Affiche uniquement les réseaux avec les valeurs renseignées

src/components/Network/EligibilityTestBox.tsx
Suppression suffisante et déplacement du loader pour éviter le CLS
=> Supprime le bouton inutile pour le test d'adresse sur la fiche réseau

docker-compose.yml
- Passage à la version 16 pour être iso avec la prod. (+/- car l'image postgis sur le hub docker est un peu en retard)
- Suppression du conteneur web car non utilisé (de ton côté aussi il me semble)
J'en ai profité pour repartir d'une base vierge (via dump) pour passer de 109 tables à 76.
=> Maj version postgres 16

src/components/Map/MapProvider.tsx, src/components/Map/components/MapLegendReseaux.tsx, src/components/Map/layers/filters.ts, src/components/Map/map-configuration.ts, src/components/NetworksList/NetworksList.tsx, src/components/ReseauxDeChaleurFilters.tsx, src/components/ui/Drawer.tsx, src/hooks/useReseauxDeChaleurFilters.tsx, src/utils/core.ts, src/utils/interval.ts
Réorganise un peu les choses pour faire fonctionner comme il faut :
- conserve uniquement les filtres RDC dans l'URL s'ils sont définis (avec au passage un niveau en moins), on espère trop rien casser si des gens ont gardé ça en favoris...)
- les filtres sont toujours typés et jamais non définis. Il y a juste les limites qui sont ajoutées par la suite. Là c'était un peu le bordel, mais l'idée d'origine était d'avoir la config de carte, puis d'obtenir la config de carte avec les limites et enfin la rendre prête à l'usage.
- le deepMergeObjects n'avait pas l'air de trop fonctionner sur les tableaux... donc j'ai modifié un peu ça.
=> Fix des filtres RDC écrasés par la map-configuration

src/server/services/manager.ts
https://trello.com/c/zwAO2z2D/1486-ne-rendre-les-demandes-visibles-ds-lespace-gestionnaire-que-qd-la-case-gestionnaires-valid%C3%A9s-est-coch%C3%A9e-sur-airtable
la demande ne sera visible sur l’espace gestionnaire qu’une fois la case Gestionnaires validés cochée
=> Gestionnaires valides

scripts/networks/commands.ts, scripts/networks/download-network.ts, scripts/networks/geometry-operations.ts, scripts/networks/geometry-updates.ts, src/components/Map/components/tools/LinearHeatDensityTool.tsx, src/components/dashboard/professionnel/ProEligibilityTestItem.tsx, src/server/db/kysely/database.ts, src/server/db/migrations/20250327000005_add_networks_date_actualisation.ts, src/utils/date.ts
- La suite + un fix de #1040
- L'idée est d'ajouter un champ date qui sera mis à jour quand on modifie la géométrie (ou on considède que le tracé est à jour).
- Encore une fois, ça va être un peu chiant pour ces histoires de migration car je dois changer des colonnes, or les migrations ne sont pas appliquées sur les review app et je vais devoir copier / dumper les données sur dev pour faire review par Florence...
=> Remplissage airtable date actualisation

.talismanrc, src/components/connexion/Form.styles.ts, src/components/connexion/NewPasswordForm.tsx, src/components/connexion/ResetPasswordForm.tsx, src/components/form/react-form/useForm.tsx, src/pages/api/password/change.ts
Si jamais quelqu’un se crée un compte, mais ne clique pas sur le lien de confirmation envoyé par email, alors il ne pourra jamais se connecter, car son compte existe mais n’est pas validé.
J’ai pris le parti d’utiliser l’ecran de rinitialisation du mot de passe
En effet, celui-ci envoie déjà un lien par email qui doit être cliqué, on est donc sur, quend l’utilisateur recrée un nouveau mot de passe, qu’il a le bon email et donc on l’active
J'en ai profité pour utiliser `useForm` pour supprimer un peu de code legacy
=> Permettre de réenvoyer un lien de confirmation d'email

package.json, src/pages/api/airtable/records/index.ts, src/server/email/index.tsx, src/server/email/react-email/index.tsx, src/server/email/react-email/templates/creation-demande.tsx, src/server/email/react-email/templates/tests/creation-demande_copropriete_collectif_inf100m.tsx, src/server/email/react-email/templates/tests/creation-demande_copropriete_collectif_inf200m.tsx, src/server/email/react-email/templates/tests/creation-demande_copropriete_collectif_sup200m.tsx, src/server/email/react-email/templates/tests/creation-demande_copropriete_individuel_inf200m.tsx, src/server/email/react-email/templates/tests/creation-demande_copropriete_individuel_sup200m.tsx, src/server/email/react-email/templates/tests/creation-demande_maison_individuel_inf200m.tsx, src/server/email/react-email/templates/tests/creation-demande_maison_individuel_sup200m.tsx, src/server/email/react-email/templates/tests/creation-demande_paris_copropriete_collectif_inf100m.tsx, src/server/email/react-email/templates/tests/creation-demande_paris_copropriete_collectif_inf60m.tsx, src/server/email/react-email/templates/tests/creation-demande_paris_copropriete_collectif_sup100m.tsx, src/server/email/react-email/templates/tests/creation-demande_paris_copropriete_individuel_inf100m.tsx, src/server/email/react-email/templates/tests/creation-demande_paris_copropriete_individuel_sup100m.tsx, src/server/email/react-email/templates/tests/creation-demande_paris_tertiaire_collectif_inf100m.tsx, src/server/email/react-email/templates/tests/creation-demande_paris_tertiaire_collectif_inf60m.tsx, src/server/email/react-email/templates/tests/creation-demande_paris_tertiaire_collectif_sup100m.tsx, src/server/email/react-email/templates/tests/creation-demande_paris_tertiaire_individuel_inf100m.tsx, src/server/email/react-email/templates/tests/creation-demande_paris_tertiaire_individuel_sup100m.tsx, src/server/email/react-email/templates/tests/creation-demande_tertiaire_collectif_inf100m.tsx, src/server/email/react-email/templates/tests/creation-demande_tertiaire_collectif_inf200m.tsx, src/server/email/react-email/templates/tests/creation-demande_tertiaire_collectif_sup200m.tsx, src/server/email/react-email/templates/tests/creation-demande_tertiaire_individuel_inf200m.tsx, src/server/email/react-email/templates/tests/creation-demande_tertiaire_individuel_sup200m.tsx, src/services/airtable.ts, src/types/AddressData.d.ts
- Envoi des emails à la création des demandes plutôt qu'avec les automatisations airtable (qui seront à désactiver au moment du déploiement)
- Gestion des 20 cas différents avec le template.
- via dev:email les différents cas sont visibles dans le sous-dossier tests
=> Envoi des emails à la création des demandes

.talismanrc, scripts/helpers/geo.ts, scripts/networks/commands.ts, scripts/opendata/create-opendata-archive.sh, src/server/helpers/file.ts, src/services/TrelloService.ts, src/utils/geo.ts
- gestion automatique des géométries qui ne sont pas en Multi
- ajout de couleurs pour afficher les labels des cartes Trello
- revue de l'affichage un peu pour être plus clair (bon c'est pas encore trop ça...)
- ajout d'une action pour passer un fichier (quand on doit faire des choses à la main)
Il y a au moins un cas où j'ai pas pu utiliser directement la CLI trello. Quand je voulais ajouter des PDP avec un id_sncu (car il faut faire les liens).
un équivalent de `pnpm cli geom insert pdp 0 1234C`
Pour le moment j'ai fait à la main en utilisant l'action skip.
=> Amélioration intégration traces

scripts/networks/geometry-operations.ts
\+ une requête manuelle à faire la prochaine fois qu'on maj les données
```sql
update reseaux_de_chaleur
set geom = ST_Force2D(geom)
WHERE ST_CoordDim(geom) = 3;
update zones_et_reseaux_en_construction
set geom = ST_Force2D(geom)
WHERE ST_CoordDim(geom) = 3;
```
=> Supprime la 3e dimension lors des manip de géométries
