betagouv/france-chaleur-urbaine

- src/components/Map/Map.tsx
if wanted, add in .env.local
`NEXT_PUBLIC_MAP_ORIGIN=https://france-chaleur-urbaine.beta.gouv.fr
`
> feat(map): Choose map origin via .env

- .env
- src/components/Ressources/Contents/Simulator.tsx
- Maj du prix spot CEE par 8.42 comme indiqué par Florence.
- J'ai supprimé la variable d'environnement, qui utilisait une valeur mauvaise en plus (le parsing donnait 6). J'ai vérifié en prod cette variable d'env ne semble pas utilisée ailleurs.
> feat: update cee

- src/components/Coproprietaire/UseCase.tsx
- src/data/coproprietaire/user-experience.js
- src/data/villes/user-experience.js
- src/pages/professionnels.tsx
#626  était un peu trop rapide. En fait il y a d'autres endroits où des cas concrets sont utilisés.
> fix: update cee example

- src/components/Map/Map.style.tsx
- src/components/Map/Map.tsx
- src/pages/carte-collectivite.tsx
- src/pages/charleville-mezieres.tsx
- src/pages/dalkia.tsx
- src/pages/engie.tsx
- src/pages/map.tsx
- src/pages/viaseva.tsx
- src/services/iframe.ts
Pour théoriquement arriver à :
> feat: add a gray border to the map iframe

- README.md
- docker-compose.yml
- docker/db/Dockerfile
3 changements :
- maj version postgres pour correspondre à celle de prod (14)
- ajout d'un volume explicite pour postgresql dans le docker-compose.yml
- maj de la procédure d'installation pour être complète. (certaines étapes seront probablement améliorées dans le futur !)
> chore: update dev env install procedure

- docker-compose.yml
- docker/postgresql.conf
Config par défaut PG 14 extraite du conteneur.
Permettra par exemple d'augmenter la taille des buffers si on décide de faire quelques grosses requêtes en local.
Je n'ai pas modifié la config car les paramètres optimum ne sont pas encore connus et cela permettra de tracer les modifications du fichier, si jamais on en fait.
En attendant de mon côté j'ai une conf spéciale que je ne commit pas.
> chore: add a custom default postgres configuration

- src/core/infrastructure/repository/addresseInformation.ts
- src/pages/api/map/bulkEligibilityStatus/index.ts
- src/pages/api/map/cityNetwork.ts
- src/pages/api/map/eligibilityStatus.ts
- src/pages/api/v1/eligibility.ts
> chore: fix typo elibibility

- scripts/bdnb/export-batiments-summary.sh
- scripts/bdnb/prepare-batiments-summary.sh
Basé sur #631, ajoute les requêtes en rapport avec le parc immobilier.
> feat: export donnees parc etat

- src/components/Statistics/Statistics.style.ts
- src/components/Statistics/Statistics.tsx
- src/data/statistics.ts
- Maj des stats au 1er janvier 2024 par Florence.
- \+ séparation visuelle du cumul des téléchargements de tracés qui est dynamique.
> feat: update stats

- src/components/HeadSliceForm/HeadSliceForm.tsx
- src/pages/api/map/bulkEligibilityStatus/index.ts
- src/pages/api/map/summary.ts
En voulant ingestiguer un problème de fichier en erreur, voici quelques améliorations, notamment au niveau du logging. Maintenant, chaque type d'action est loggé :
- nouveau test
- test existant, en erreur
- test existant avec résultat
> chore: improve logging for bulk eligibility tests

- src/components/ContactForm/index.tsx
- src/components/addressAutocomplete/components/AddressInput.tsx
- src/pages/api/airtable/records/index.ts
- Amélioration de la page Contact (vu avec Caroline et Florence)
- Ajout d'autocomplete à off sur le formulaire de recherche d'adresse (chez moi j'ai mon gestionnaire de mont de passe 1password qui s'active automatiquement, donc ça pourrait être le cas ailleurs)
- Ajout d'un log pour les tests d'éligibilité, pour logger toutes les infos (non personnelles) et avoir une meilleure vision sur le traitement effectué et les données récupérées
> refactor: minor improvements

- src/components/Map/components/SummaryBoxes.tsx
- src/utils/browser.ts
- src/utils/date.ts
~J'ai pas touché au style du bouton qui est le même que pour le 1er onglet, et positionné en absolu... mais ça passe~ :wink: 
Bon finalement si, c'était demandé par Florence. :grin: 
Voici le rendu final :
> feat: export tracé densité linéaire en geojson

- src/components/Network/Network.tsx
https://trello.com/c/zCTpgqzG/890-fiches-par-r%C3%A9seau-mettre-non-connu-qd-pas-dinfos-exemple
> Empty values on network page

- src/pages/api/map/bulkEligibilityStatus/index.ts
Fix date format pour pouvoir importer les anciennes valeurs
> fix: send date to airtable 'test en masse'

- src/components/Map/Map.tsx
Corrigé via le site hellio en intégrant mon iframe locale. (J'ai changé la réponse de la page et ça marche plutôt bien !)
> fix: wrong map size at initialisation

- src/pages/collectivites-et-exploitants.tsx
https://trello.com/c/pRxX66MA/1061-coquilles-%C3%A0-coriger
> fix: coquilles page exploitants

- src/components/Admin/BulkEligibility.tsx
- src/components/Admin/Users.styles.ts
- src/components/Admin/Users.tsx
Réinitialise la page à 1 quand on change le filtre dans l'administration + arrangement du style des inputs (un peu brut, mais un peu meilleur selon moi)
Avant après :
<div>
</div>
> fix: reset admin pagination on filter

- src/components/Map/Map.tsx
- src/hooks/useURLParamOrLocalStorage.ts
- src/pages/carte.tsx
- src/utils/debounce.ts
Enregistre le mode pro dans l'URL afin de pouvoir partager plus facilement la carte dans une vue prédéfinie.
Bientôt (un jour) viendront les couches actives qui sont aussi nécessaires.
> feat: save the pro mode in the URL

- next.config.js
- src/services/iframe.ts
Corrige l'intégration de la page idex dans une iframe.
> fix: CSP pour l'iframe idex

- src/components/Statistics/Statistics.tsx
- src/data/statistics.ts
2 tickets en 1 sur la page stats :
- maj des chiffres
- maj du texte d'une infobulle
> feat: update stats data

- scripts/bdnb/readme.md
Demandé par Florence, histoire de documenter un minimum rapidement.
> doc: export données bdnb maille epci

- src/components/EligibilityForm/EligibilityFormMessageConfirmation.tsx
- src/components/connexion/NewPasswordForm.tsx
- src/helpers/server.ts
- src/hooks/useContactFormFCU.ts
- src/pages/api/airtable/records/[id].ts
- src/pages/api/airtable/records/index.ts
- src/pages/api/dpe/index.ts
- src/pages/api/managerEmail.ts
- src/pages/api/map/cityNetwork.ts
- src/pages/api/map/eligibilityStatus.ts
- src/pages/api/map/network.ts
- src/pages/api/map/summary.ts
- src/pages/api/modification-reseau.ts
- src/pages/api/password/change.ts
- src/pages/api/password/reset.ts
- src/pages/api/statistiques/contacts.ts
- src/pages/api/v1/demands/[key].ts
- src/pages/api/v1/eligibility.ts
- src/pages/api/v1/users/[key].ts
- src/pages/reset-password/[token].tsx
- src/services/errors.ts
- src/utils/validation.ts
- src/utils/validation/password.ts
J'ai des doutes sur le fonctionnement de la route /api/airtable/records, qui retourne des "ids" qui sont des objets airtable...
> refactor: more validation

- src/data/contents/README (4).md
> fix: correction lien enquête ifop dans un article

- src/services/analytics.ts
Pb actuel : si le matomo beta est KO, alors le script peut être en cours de chargement et donc le formulaire ab testing ne s'affiche jamais.
Maintenant, on timeout après 2s pour passer de statut pending à error et afficher la variation par défaut.
> fix: handle matomo not responding for ab testing

- src/components/Network/Network.tsx
- src/services/analytics.ts
Tracking du téléchargement des schémas directeurs, avec id réseau et nom du fichier en paramètre.
> feat: tracking téléchargement schémas directeurs

- src/core/infrastructure/repository/addresseInformation.ts
Légende actualisée dans le fichier résultat de test en masse.
> feat: maj légende fichier test en masse

- next.config.js
- scripts/networks/download-network.ts
- src/components/EligibilityForm/EligibilityFormContact.tsx
- src/components/EligibilityForm/EligibilityResults.tsx
- src/components/Manager/Addresse.tsx
- src/components/Map/components/CardSearchDetails.tsx
- src/core/infrastructure/repository/addresseInformation.ts
- src/core/infrastructure/repository/pdp.ts
- src/db/migrations/20240617000000_add_networks_has_pdp.ts
- src/helpers/airtable.ts
- src/pages/api/demands/index.ts
- src/pages/api/v1/eligibility.ts
- src/types/HeatNetworksResponse.d.ts
- src/types/Summary/Demand.d.ts
- Ajout des messages [selon les cas](https://trello.com/c/yAdpYQCJ/1172-ajout-phrase-r%C3%A9seau-class%C3%A9-ds-r%C3%A9ponse-formulaire-%C3%A0-traiter-apr%C3%A8s-le-ticket-relatif-%C3%A0-linfo-haspdp-dans-airtable) (vu avec Florence)
- Renommage partout zdp => pdp
> feat: maj texte pdp

- src/components/GenericContent/CoutsChauffageUrbain.tsx
- src/components/Ressources/Contents/SimulateurCoutRaccordement.tsx
- src/pages/index-fioul-campaign.tsx
- src/pages/index-gaz-campaign-1.tsx
- src/pages/index-gaz-campaign-2.tsx
- src/pages/professionnels.tsx
Le nouveau simulateur compatible DSFR est désormais intégré sur les autres pages (copro + professionnels)
> feat: maj intégration simulateur cout raccordement

- src/components/Network/Network.tsx
- Revue des conditions pour les données fluide caloporteur - * pour gérer soit un nombre, soit oui/non, soit rien (non connu)
> fix: revue affichage données fluide caloporteur

- src/components/ConsentBanner/index.tsx
Régression suite à la migration DSFR.
> fix: cache la ConsentBanner quand iframe

- src/components/shared/page/SimplePage.tsx
> feat: ajout d'une entrée Nos statistiques au menu Notre service

- src/components/Manager/Comment.tsx
- src/components/Manager/Manager.tsx
- src/components/ui/Table.tsx
- Corrige le champ commentaires qui est cassé depuis la migration DSFR.
Encore à corriger :
> fix: permet la modification de la colonne commentaires

- .husky/pre-commit
- .talismanrc
- README.md
- package.json
- yarn.lock
- Ajoute talisman en hook precommit qui permet de lever une erreur si on commit un secret (s'il est détecté)
- ~Manque une petite commande pour ajouter une exception~
- Ajout d'une commande `yarn talisman:add-exception` pour ignorer une alerte.
> Ajoute talisman en hook pre-commit

- src/components/Theme/ThemeProvider.tsx
- src/pages/_document.tsx
Suite à l'utilisation du DSFR et à la tentative infructueuse https://github.com/betagouv/france-chaleur-urbaine/pull/840. Voici une nouvelle résolution qui force la valeur dans le local storage
> Force l'utilisation du mode light

- src/components/EligibilityForm/components/ContactInformation.tsx
- Ajout des validations sur les champs requis conditionnels 
- Nom de la Structure accompagnée obligatoire
> Form demand : message for required conditionnals fields + required 'Structure accompagnée'

- .talismanrc
- src/components/Map/Map.style.tsx
- src/components/Map/Map.tsx
- src/components/Map/components/MapSearchForm.tsx
- src/components/Theme/ThemeProvider.tsx
- src/components/ui/Button.tsx
- src/types/globale.d.ts
Reaffinage de la carte pour que'elle s'affiche correctement dans les iframes
> Carte iframe

- .talismanrc
- src/components/Map/Map.style.tsx
- src/components/Map/Map.tsx
- src/components/Map/components/MapLegendReseaux.tsx
- src/components/Map/components/SimpleMapLegend.tsx
- src/components/Map/components/tools/BuildingsDataExtractionTool.tsx
- src/components/Map/components/tools/LinearHeatDensityTool.tsx
- src/components/Map/map-layers.ts
- src/pages/carte.tsx
- src/services/Map/map-configuration.ts
- src/services/analytics.ts
- src/services/tiles.config.ts
Après la première version de la carte, quelques ajustements sont nécessaires
> Carte review

- src/components/Map/components/tools/BuildingsDataExtractionTool.tsx
- src/components/Map/components/tools/DistancesMeasurementTool.tsx
- src/components/Map/components/tools/LinearHeatDensityTool.tsx
Dessin si rien d'actif, sinon juste bouton Ajouter
+ quelques règles de gestion
Ça devient complexe... :exploding_head:
> Mode dessin direct dans les outils

- src/components/EligibilityForm/EligibilityFormContact.tsx
- src/components/EligibilityForm/EligibilityResults.tsx
- src/services/analytics.ts
> Suppression AB testing formulaire demandes

- src/components/Map/Map.style.tsx
- src/components/Map/Map.tsx
- src/components/ui/Icon.tsx
> Fix style rotation icones

- package.json
- src/components/ComparateurPublicodes/ParametresDuBatimentGrandPublic.tsx
- src/components/ComparateurPublicodes/ParametresDuBatimentTechnicien.tsx
- yarn.lock
Corrige le P1' NaN dû à la part consommation d'électricité erronée.
> Hotfixes comparateur

- src/components/Network/Network.tsx
- src/services/Map/conso.ts
Et autoriser les données en 0, notamment pour le contenu CO2
> Vérification de valeur pour afficher les infos du réseau

- .talismanrc
- src/pages/carte.tsx
- src/services/tiles.config.ts
> Ajout dernière couche à la liste des additionalLayers

- src/components/NetworksList/NetworksList.tsx
> Ajout des sources page réseaux

- .talismanrc
- src/components/Map/Map.style.tsx
- src/components/Map/Map.tsx
- src/components/Map/components/MapLegendReseaux.tsx
- src/components/Map/components/RangeFilter.tsx
- src/components/Map/components/ReseauxDeChaleurFilters.tsx
- src/components/Map/components/SimpleMapLegend.style.tsx
- src/components/Map/components/SimpleMapLegend.tsx
- src/components/ui/Accordion.tsx
- src/services/Map/map-configuration.ts
https://trello.com/c/4Brl67jr/1319-ajouter-bouton-sticky-dans-les-filtres-sur-la-carte-pr-r%C3%A9initialiser-et-voir-la-liste-en-bas-sur-la-capture-d%C3%A9cran
> Map reset filters

- .talismanrc
- src/components/NetworksList/NetworksList.tsx
- src/components/ui/Table.tsx
Je suis passé dessus pour #891 et ai un peu amélioré le rendu pendant le chargement
> Meilleur rendu au chargement des données pour éviter le CLS

- package.json
- src/helpers/fileio.spec.ts
- src/helpers/fileio.ts
- yarn.lock
Car test flaky quand plateforme en 503
Bon ça n'aide pas si la plateforme a de gros problèmes > 1 minutes, ce qui semble être le cas en ce moment...
> Ajout d'un retry avec axios pour file.io

- src/components/NetworksList/NetworksFilters.tsx
- src/types/NetworksFilters.tsx
Pour les filtres gestionnaires, c'est Engie Solutions qui doit être affiché mais Engie pour le filtrage/
> Gestionnaires - value and label could be different from each other

- src/components/NetworksList/NetworksList.tsx
- src/services/heatNetwork.ts
Typo concernant le filtrage de engie
> Fix network filters

- src/components/ComparateurPublicodes/ComparateurPublicodes.tsx
https://trello.com/c/Unfm6LhD/1335-cr%C3%A9er-les-pages-tests-pour-les-villes-sans-r%C3%A9seau
> Affiche message quand le réseau n'a pas de prix moyen sur le comparateur

- src/components/ComparateurPublicodes/ComparateurPublicodes.tsx
- src/components/ComparateurPublicodes/Placeholder.tsx
- src/components/ContactForm/index.tsx
- src/components/shared/page/Banner.tsx
- src/components/shared/page/SimplePage.tsx
- src/components/ui/Notice.tsx
- src/components/ui/NoticeRemovable.tsx
- src/environment.d.ts
- src/hooks/index.ts
- src/hooks/useLocalStorage.ts
- src/hooks/usePersistedState.ts
Voir ici https://trello.com/c/m0YlrTOL/1343-alerte-au-dessus-du-header-renvoyant-vers-le-comparateur-petites-modifications
> Comparateur modifs

- src/components/ui/Notice.tsx
Pour faire passer le build sur le comparateur
> Fixe typescript pour la Notice

- src/components/ui/Newsletter.tsx
- src/core/infrastructure/repository/communeAPotentiel.ts
- src/pages/collectivites-et-exploitants/potentiel-creation-reseau/[[...slug]].tsx
- src/services/analytics.ts
https://trello.com/c/NRWUtKjp/1352-petites-modifs-pages-villes-sans-r%C3%A9seau
> Modifications mineures villes à potentiel

- src/components/Map/components/ModalCarteFrance.tsx
- src/components/ui/Modal.tsx
- src/hooks/useQueryFlag.tsx
Il ya aussi un problème avec la DSFR modal
Quand on utilise useIsModalOpen, il semble que la valeur ne change pas toujours
> Fixe l'affichage du potentiel de densification dans la modale

- src/components/Map/components/tools/BuildingsDataExtractionTool.tsx
- src/components/Map/components/tools/DistancesMeasurementTool.tsx
- src/components/Map/components/tools/LinearHeatDensityTool.tsx
- src/services/analytics.ts
Le tracking avait été un peu omis suite au refacto des outils.
Maintenant, globalement tous les boutons / actions importantes sont trackées.
> Tracking Matomo des outils de la carte

- docs/mise_a_jour_donnees_traces_fcu.md
Quelques maj de commandes suite au nouvel export de Sébastien.
> Maj doc maj tracés

- src/core/infrastructure/repository/communeAPotentiel.ts
- src/pages/collectivites-et-exploitants/potentiel-creation-reseau/[[...slug]].tsx
- src/services/analytics.ts
- prise en compte des réseaux futurs
- réduction géométrie de la commune à -150m pour exclure les tracés en bordures de commune
- meilleure utilisation de l'API kysely (% le typage qui est en string côté driver)
> Revue des conditions pour les communes à potentiel

- DEVELOPMENT.md
- src/pages/ressources/outils.tsx
Il y avait une autre occurrence dans un article, mais c'est maj avec #944
> Maj lien vers l'API FCU

- src/components/NetworksList/NetworksList.tsx
> Fix affichage données même si 0 sur la liste des réseaux

- src/components/ReseauxDeChaleurFilters.tsx
> Espacement entre les filtres énergies mobilisées

- src/pages/villes/[ville].tsx
J'ai arrangé le SSG en m'inspirant de la page potentiel création réseau et suite à notre discussion SEO. :)
A priori tu n'as pas encore touché à ça sur ta branche SEO , mais il manque peut-être des commits. :shrug:
> Gestion du cas ville non trouvée pour /villes/*

- src/components/Cities/Networks.styles.ts
- src/components/Cities/Networks.tsx
- src/components/MarkdownWrapper/MarkdownWrapper.style.tsx
- src/components/Ressources/config.tsx
- src/components/SEO.tsx
- src/components/Statistics/Statistics.style.ts
- src/components/Statistics/Statistics.tsx
- src/components/shared/page/SimplePage.tsx
- src/data/contents/README (35).md
- src/pages/carte.tsx
- src/pages/chauffage-urbain.tsx
- src/pages/collectivites-et-exploitants.tsx
- src/pages/connexion.tsx
- src/pages/index.tsx
- src/pages/qui-sommes-nous.tsx
- src/pages/ressources/[ressource].tsx
Quelques ajustements mineurs
- affichage sur la page stats et ville
- suffixe SEO
> Fix after deploy

- src/components/Map/Map.tsx
> Ajout d'un bouton pour vider les adresses recherchées

- src/components/shared/page/SimplePage.tsx
- src/pages/carte.tsx
Pour éviter des problèmes de scroll avec les popups de la carte.
Et aussi footer inutile dans cette page.
> Suppression du footer sur la carte

- src/components/Map/Map.style.tsx
- src/components/Map/Map.tsx
- src/components/Map/StyleSwitcher/index.ts
- src/components/Map/osm.config.json
Pour être plus robuste aux changements de style côté geo datagouv
> Embarque les styles OSM bright

- src/components/Cities/Header.tsx
- src/components/ComparateurPublicodes/Placeholder.tsx
- src/components/Network/Network.tsx
- src/components/Partners/Partners.tsx
- src/components/ui/Table.tsx
- src/pages/collectivites-et-exploitants.tsx
- src/pages/index-fioul-campaign.tsx
- src/pages/index-gaz-campaign-1.tsx
- src/pages/index.tsx
- src/pages/professionnels.tsx
- src/styles/globals.css
Tailwind insere un reset css, ce qui a provoqué des pb mineurs, notamment sur les images.
Cette PR fixe ces problèmes.
Je suis repassé sur tous les écrans que j'ai trouvé
> Fixe les problèmes d'affichage après avoir intégré tailwind

- src/components/Map/components/SimpleMapLegend.style.tsx
Passe de ça ![image](https://github.com/user-attachments/assets/468a4a4a-9c91-409e-8eb4-66d6ba3cb224)
à ça ![Screenshot 2025-01-21 at 14 32 03](https://github.com/user-attachments/assets/784a468e-52f2-4f40-b8d2-529fb87ed78d)
> Rend le outline mieux dessiné sur la légende de la carte

- src/components/Statistics/Statistics.style.ts
- src/components/Statistics/Statistics.tsx
- src/data/statistics.ts
J'en profite pour migrer les tooltips sur la page stats vers celles du DSFR
> Mise à jour des statistiques

- src/pages/collectivites-et-exploitants/potentiel-creation-reseau/[[...slug]].tsx
- src/pages/iframe/potentiel-creation-reseau/[[...slug]].tsx
J'ai aussi ajouté un lien pour revenir sur france chaleur urbaine sur le logo en lui-meme
> Ajoute le logo sur l'iframe des communes sans réseaux et revoit les espacements

- src/components/Manager/ManagerHeader.styles.ts
- src/components/Manager/ManagerHeader.tsx
- Suppression des 2 filtres nom et email => création d'un filtre global nom + email + réseau.
- Petit refacto pour simplifier l'écriture du filtre. Je trouve un peu chelou que le filtrage soit ici plutôt que dans le composant principal, mais bon je touche pas à cette partie. :upside_down_face:
> Unification recherche espace gestionnaire

- src/components/Map/components/SimpleMapLegend.tsx
Suite à la validation des données
> Affiche les filtres études en cours sur la carte

- src/server/services/manager.ts
- Permet de passer d'une dizaine de seconde à quelques centaines dans le meilleur des cas.
- Et log le temps de réponse des demandes espace gestionnaire pour analyse future
> perf: filtre les records directement dans airtable pour lister les demandes

- src/components/Statistics/Statistics.tsx
Au final, nous affichons les statistiques sur les 12 derniers mois
https://trello.com/c/OOW0BwMp/1442-modif-dun-chiffre-sur-page-stats
> Stats 2024

- src/components/Network/NetworkSearchInput.tsx
- src/components/Tertiaire/index.tsx
- src/components/dsfr/Header.tsx
- src/components/ui/Divider.tsx
- src/config/withSentry.ts
- src/hooks/useInitialSearchParam.ts
- src/hooks/useRouterReady.ts
- src/hooks/useURLParamOrLocalStorage.ts
- src/pages/404.tsx
- src/pages/_document.tsx
- src/pages/admin.tsx
- src/pages/admin/test-coordonnees-geographiques.tsx
- src/pages/campagnes2024.tsx
- src/pages/collectivites-et-exploitants.tsx
- src/pages/connexion.tsx
- src/pages/decret-tertiaire.tsx
- src/pages/fresnes.tsx
- src/pages/gestionnaire.tsx
- src/pages/index.tsx
- src/pages/infos-copro.tsx
- src/pages/reset-password/[token].tsx
- src/pages/reset-password/index.tsx
- src/pages/tertiaire.tsx
Mise à jour de next + named export partout pour éviter les potentiels problèmes avec Node
> Tech update

- src/components/dashboard/DashboardProfessionnel.tsx
- src/components/form/Autocomplete.tsx
- src/components/shared/page/SimplePage.tsx
- src/components/ui/TableSimple.tsx
- src/services/authentication.ts
https://trello.com/c/8GhnzLZd/1450-espace-pro-r%C3%A9gler-probl%C3%A8me-session-pour-les-onglets
- Si la session a été retrouvée une première fois sur une page connectée, on la garde aussi si on va vers une page non connectée
- Affinage du tableau (header en version tablette + taille des colonnes)
- Fixe les URLs pour la partie /pro
> Espace pro - régler problème session pour les onglets

- src/client-config.ts
- src/components/EligibilityForm/EligibilityFormContact.tsx
- src/components/connexion/LoginForm.tsx
- src/components/dashboard/DashboardProfessionnel.tsx
- src/components/shared/page/Banner.tsx
- src/components/shared/page/SimplePage.tsx
- src/environment.d.ts
- src/pages/api/auth/register.ts
- src/pages/comparateur-couts-performances.tsx
- src/pages/index.tsx
- src/pages/pro/comparateur-couts-performances.tsx
- src/pages/ressources/outils.tsx
- src/server/clock.ts
- src/server/config.ts
- src/server/db/kysely/index.ts
- src/server/helpers/logger.ts
- src/server/services/api-adresse.ts
Finalement, on ne parle plus d'environnement (car c'est un peu un détail en fait) mais de config.
On a la config serveur qui provient principalement des variables d'environnement.
Mais aussi la config client, qui contient aussi majoritairement des variables d'env basées sur NEXT_PUBLIC_*.
> Séparation des configs client et serveur

- package.json
- src/components/ComparateurPublicodes/DebugDrawer.tsx
- src/components/dashboard/professionnel/ProEligibilityTestItem.tsx
- src/components/ui/Button.tsx
- src/components/ui/TableSimple.tsx
- yarn.lock
Nouvelle version du comparateur 1.0.3 intégré
On en profite pour
- mieux afficher les tables en passant une width sur la colonne et un parametre "fluid"
- supprimer le warning sur le composant Button
> Nouvelle version du comparateur

- src/components/ComparateurPublicodes/Placeholder.tsx
- src/components/Network/Network.tsx
- src/server/db/migrations/20250317000001_increase_size_infos_complementaires.ts
- données mises à jour sur airtable et synchronisées en BDD.
- changements de labels 2022 => 2023.
> Actualisation fiches réseau suite à bibli fedene 2024

- src/components/ComparateurPublicodes/ComparateurPublicodes.tsx
- src/components/ComparateurPublicodes/Graph.tsx
- src/components/ComparateurPublicodes/ModesDeChauffageAComparer.tsx
- src/components/ComparateurPublicodes/Placeholder.tsx
- src/components/connexion/LoginForm.tsx
- src/components/connexion/RegisterForm.tsx
- src/components/shared/page/SimplePage.tsx
- src/pages/admin.tsx
- src/pages/admin/impostures.tsx
- src/pages/admin/jobs.tsx
- src/pages/admin/test-coordonnees-geographiques.tsx
- src/pages/admin/users.tsx
- src/pages/comparateur-couts-performances.tsx
- src/pages/pro/aide.tsx
- src/pages/pro/comparateur-couts-performances.tsx
- src/pages/pro/demandes.tsx
- src/pages/pro/tableau-de-bord.tsx
- src/pages/pro/tests-adresses.tsx
- src/pages/satisfaction.tsx
- src/server/authentication.ts
- Modification des textes introductifs
- Modification de l'affichage en mode grand public
- Modification des modes de chauffages sélectionnés par défaut
> Dernières modifications suite aux retours Amorce

- src/components/dashboard/professionnel/eligibility-test/CreateEligibilityTestForm.tsx
- src/components/ui/Dialog.tsx
- src/pages/pro/tests-adresses.tsx
Corrige les problèmes d'ouverture
> Utilise une modale basée sur radix-ui pour les tests en masse

- src/components/dashboard/DashboardAdmin.tsx
- src/components/shared/page/SimplePage.tsx
- src/pages/api/demands/[demandId].ts
- src/pages/api/demands/index.ts
- src/pages/api/pro-eligibility-tests/[id].ts
- src/pages/api/pro-eligibility-tests/[id]/mark-as-seen.ts
- src/pages/api/pro-eligibility-tests/[id]/rename.ts
- src/pages/pro/aide.tsx
- src/pages/pro/comparateur-couts-performances.tsx
- src/pages/pro/demandes.tsx
- src/pages/pro/tableau-de-bord.tsx
- src/pages/pro/tests-adresses.tsx
Suite à la migration à l'espace pro, l'accès aux pages pour le user demo n'était plus possible
> Espace demo

- .cursor/rules/0003-typescript.mdc
- src/components/dashboard/professionnel/ProEligibilityTestItem.tsx
- src/components/dashboard/professionnel/ProcheReseauBadge.tsx
- src/components/form/dsfr/RangeFilter.tsx
- src/components/ui/Button.tsx
- src/components/ui/Popover.tsx
- src/components/ui/TableFilter.tsx
- src/components/ui/TableSimple.tsx
- src/pages/api/pro-eligibility-tests/[id].ts
- tailwind.config.ts
Afin de faciliter l'utilisation de l'interface de tests en masse, l'ajout de filtres sur la liste d'addresses semble important.
https://trello.com/c/ZuAjuKyy/1481-test-en-masse-ajouter-des-filtres
Cette PR va
- ajouter la fonctionnalité de filtrage sur TableSimple
- ajouter les filtres sur la liste
Bonus:
Si cela parait important, on pourrait aussi
- gerer les filtres dans l'URL
> Filtrage des test d'éligibilité

- src/components/GenericContent/IframeIntegration.tsx
- src/components/IFrame/Form/IFrameLink.styles.ts
- src/components/IFrame/Form/IFrameLink.tsx
- src/components/IFrame/Map/IFrameMapIntegrationForm.styles.ts
- src/components/IFrame/Map/IFrameMapIntegrationForm.tsx
- src/pages/collectivites-et-exploitants.tsx
- src/pages/communique-de-presse-janvier2024.tsx
- tailwind.config.ts
Afin de récolter + de backlinks et ainsi améliorer la notoriété du site vis à vis de Google, on l'ajoute directement dans le code à copier-coller
j'en profite aussi poru revoir le design de la page collectivité et exploitants avec les nouvelles sections
> Backlink dans le code de l'iframe

- src/components/ComparateurPublicodes/ComparateurPublicodes.tsx
- src/components/ComparateurPublicodes/Graph.tsx
- src/components/ui/Tooltip.tsx
https://trello.com/c/6xRu2kkM/1492-comparateur-cas-o%C3%B9-les-donn%C3%A9es-tarifaires-sont-non-dispos?completedInviteSignup=1
> Distingue les valeurs de CO2 et de cout quand le cout du réseau n'est pas spécifié

- src/components/dashboard/professionnel/ProEligibilityTestItem.tsx
- src/components/shared/page/SimplePage.tsx
- src/pages/admin/tests-adresses.tsx
- src/pages/api/admin/pro-eligibility-tests.ts
- src/pages/api/pro-eligibility-tests/[id].ts
- Ajout d'un bouton pour mettre en relation les utilisateurs et Erwan. Le texte est encore à définir.
- Ajout d'une page admin pour visualiser tous les tests en masse créés
> Mise en relation professionnels fcu

- src/pages/admin/users.tsx
- Pour tester les choses un peu plus facilement, nouvelle action pour faire une imposture avec le même profil qu'un utilisateur.
- Améliore un peu l'affichage du tableau des utilisateurs
> Add imposture role user

- src/components/ContributionForm/ContributionForm.tsx
- src/pages/api/contribution.ts
- src/pages/contribution.tsx
Quelques petits changement (cf commits). Pas de refactoring pour garder la PR simple. :)
> Maj phrases formulaire contribution

- src/components/Map/Map.style.tsx
- src/components/Map/Map.tsx
- src/components/Map/components/MapLegendReseaux.tsx
- src/components/Map/components/SimpleMapLegend.tsx
- src/pages/carte-reseaux-de-chaleur-et-froid.tsx
- src/types/TypeLegendLogo.ts
Pour montrer à quoi pourrait ressembler un site dédié
> Carte dédiée au Cerema

- .talismanrc
- docs/mise_a_jour_donnees_fcu.md
- scripts/networks/commands.ts
- scripts/networks/geometry-operations.ts
Pour rendre les scripts de plus en plus facile à utiliser
> Mise à jour CLI import réseaux de chaleur

- src/components/ComparateurPublicodes/ComparateurPublicodes.tsx
- src/components/ComparateurPublicodes/DebugDrawer.tsx
- src/components/ComparateurPublicodes/Graph.tsx
- src/components/NetworksList/NetworksList.tsx
- src/components/ui/ButtonExport.tsx
- src/utils/export.ts
Afin que les données puisse être réutilisées par des bureaux d'études.
> Ajout de la fonctionnalité d'export sur le comparateur

- src/components/ComparateurPublicodes/ComparateurPublicodes.tsx
- src/components/ComparateurPublicodes/Configuration.tsx
- src/components/form/Autocomplete.tsx
- src/components/ui/CrudDropdown.tsx
- src/server/db/kysely/database.ts
- src/server/db/migrations/20250527115141_email_templates_add_address.ts
- src/server/services/comparateur/configuration.ts
Après plusieurs retours, l'adresse est un point important qu'il faut garder en mémoire
> Ajout de l'adresse aux configurations du comparateur

- README.md
Documente un peu plus l'architecture de FCU pour les nouveaux arrivants.
> Ajout doc architecture

- package.json
- pnpm-lock.yaml
- src/components/Theme/ThemeProvider.tsx
- src/components/ui/CallOut.tsx
- src/pages/_app.tsx
- src/pages/_document.tsx
Objectifs :
- maj version next.js
- activation turbo au build (et vérifier que le changement de page fonctionne)
- maj version react-dsfr
- maj autres versions ?
Pour le moment, la maj vers next.js 15.4.1 casse tout à cause des imports CSS globaux qui sont dans _app, mais next.js se vautre.
> Maj versions DSFR

- .talismanrc
- scripts/bootstrap/tables.ts
- scripts/data-import/adapters/zones-opportunite-fort-froid.ts
- scripts/data-import/adapters/zones-opportunite-froid.ts
- scripts/data-import/index.ts
- scripts/tiles/adapters/zones-opportunite-fort-froid.ts
- scripts/tiles/adapters/zones-opportunite-froid.ts
- scripts/tiles/index.ts
- src/components/Map/components/SimpleMapLegend.tsx
- src/components/Map/layers/zonesPotentielFroid.tsx
- src/components/Map/map-configuration.ts
- src/components/Map/map-layers.ts
- src/pages/carte.tsx
- src/server/db/kysely/database.ts
- src/server/db/migrations/20250826000000_add_table_zones_potentiel.ts
- src/server/services/tiles.config.ts
- src/services/analytics.ts
4 tables à copier en dev/prod :
```sh
pnpm db:push:dev zone_a_potentiel_froid zone_a_potentiel_fort_froid zone_a_potentiel_froid_tiles zone_a_potentiel_fort_froid_tiles
```
> Ajout zones potentiel froid

- src/pages/contact.tsx
> Ajout lien vers le formulaire de contribution sur la page contact
